### ISSUE TITLE
更新维护说明

### ISSUE THREAD

**Issue by CharesFang** [CharesFang/WeiboSpider#12]
**额，最近又懒下去了，功能随缘扩展，文档随缘写，有需求请疯狂push我**

**Comment by myWillison** [comment]
可否增加爬取 搜索页面 的功能（输入关键词，爬取搜索页面的所有博文）

**Comment by CharesFang** [comment]
> 可否增加爬取 搜索页面 的功能（输入关键词，爬取搜索页面的所有博文）

原来实现过这个功能，实现逻辑同`user_info` and `tweet_info`，有兴趣PR吗，最近我可能不太有空闲的时间，不好意思

**Comment by CharesFang** [comment]
> 可否增加爬取 搜索页面 的功能（输入关键词，爬取搜索页面的所有博文）

可以参考[v1.0](https://github.com/CharesFang/WeiboSpider/blob/v1.0/WeiboSpider/spiders/KeyWordsSpider.py)这个链接中的代码，不过1.0版本太难用了，所有我后来进行了重构，但是没有把这块儿功能迁移过来

**Comment by CharesFang** [comment]
> **额，最近又懒下去了，功能随缘扩展，文档随缘写，有需求请疯狂push我**

最近太忙了，有机会一定把没有弄完的文档+进一步重构
